Traceback (most recent call last):
  File "apps/frappe/frappe/auth.py", line 119, in __init__
    self.make_session(resume=True)
  File "apps/frappe/frappe/auth.py", line 207, in make_session
    frappe.local.session_obj = Session(
  File "apps/frappe/frappe/sessions.py", line 238, in __init__
    self.resume()
  File "apps/frappe/frappe/sessions.py", line 310, in resume
    validate_ip_address(self.user)
  File "apps/frappe/frappe/auth.py", line 420, in validate_ip_address
    ip_list = get_restricted_ip_list(user_info)
  File "apps/frappe/frappe/core/doctype/user/user.py", line 1180, in get_restricted_ip_list
    if not user.restrict_ip:
AttributeError: 'NoneType' object has no attribute 'restrict_ip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 83, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 171, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "apps/frappe/frappe/auth.py", line 34, in __init__
    self.set_session()
  File "apps/frappe/frappe/auth.py", line 70, in set_session
    frappe.local.login_manager = LoginManager()
  File "apps/frappe/frappe/auth.py", line 124, in __init__
    self.get_user_info()
  File "apps/frappe/frappe/auth.py", line 165, in get_user_info
    self.user_type = self.info.user_type
AttributeError: 'NoneType' object has no attribute 'user_type'

Updating Dashboard for frappe
Updating Dashboard for erpnext
Updating Dashboard for frappe
Updating Dashboard for erpnext
Traceback (most recent call last):
  File "apps/frappe/frappe/auth.py", line 119, in __init__
    self.make_session(resume=True)
  File "apps/frappe/frappe/auth.py", line 207, in make_session
    frappe.local.session_obj = Session(
  File "apps/frappe/frappe/sessions.py", line 238, in __init__
    self.resume()
  File "apps/frappe/frappe/sessions.py", line 310, in resume
    validate_ip_address(self.user)
  File "apps/frappe/frappe/auth.py", line 420, in validate_ip_address
    ip_list = get_restricted_ip_list(user_info)
  File "apps/frappe/frappe/core/doctype/user/user.py", line 1180, in get_restricted_ip_list
    if not user.restrict_ip:
AttributeError: 'NoneType' object has no attribute 'restrict_ip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 83, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 171, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "apps/frappe/frappe/auth.py", line 34, in __init__
    self.set_session()
  File "apps/frappe/frappe/auth.py", line 70, in set_session
    frappe.local.login_manager = LoginManager()
  File "apps/frappe/frappe/auth.py", line 124, in __init__
    self.get_user_info()
  File "apps/frappe/frappe/auth.py", line 165, in get_user_info
    self.user_type = self.info.user_type
AttributeError: 'NoneType' object has no attribute 'user_type'

Updating Dashboard for frappe
Updating Dashboard for erpnext
Updating Dashboard for frappe
Updating Dashboard for erpnext


\b'{"customer": "John Doe", "items": [{"item_code": "Item001", "qty": 5}]}'n



\b'{"customer": "John Doe", "items": [{"item_code": "Item001", "qty": 5}]}'n



\b'{"customer": "John Doe", "items": [{"item_code": "Item001", "qty": 5}]}'n

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 85, in application
    frappe.api.validate_auth()
  File "apps/frappe/frappe/api.py", line 178, in validate_auth
    validate_auth_via_api_keys(authorization_header)
  File "apps/frappe/frappe/api.py", line 235, in validate_auth_via_api_keys
    validate_api_key_secret(api_key, api_secret, authorization_source)
  File "apps/frappe/frappe/api.py", line 253, in validate_api_key_secret
    doc_secret = frappe.utils.password.get_decrypted_password(doctype, doc, fieldname="api_secret")
  File "apps/frappe/frappe/utils/password.py", line 65, in get_decrypted_password
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 528, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 445, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.AuthenticationError: Password not found for User None api_secret

Traceback (most recent call last):
  File "apps/frappe/frappe/modules/utils.py", line 245, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
  File "apps/frappe/frappe/__init__.py", line 1330, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'frappe.core.doctype.yourresourcetype'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 142, in handle
    doc = frappe.get_doc(data).insert()
  File "apps/frappe/frappe/__init__.py", line 1187, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 72, in get_doc
    controller = get_controller(doctype)
  File "apps/frappe/frappe/model/base_document.py", line 82, in get_controller
    site_controllers[doctype] = _get_controller()
  File "apps/frappe/frappe/model/base_document.py", line 64, in _get_controller
    module = load_doctype_module(doctype, module_name)
  File "apps/frappe/frappe/modules/utils.py", line 249, in load_doctype_module
    raise ImportError(msg) from e
ImportError: Module import failed for YourResourceType, the DocType you're trying to open might be deleted.<br> Error: No module named 'frappe.core.doctype.yourresourcetype'

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 142, in handle
    doc = frappe.get_doc(data).insert()
  File "apps/frappe/frappe/model/document.py", line 252, in insert
    self.check_permission("create")
  File "apps/frappe/frappe/model/document.py", line 195, in check_permission
    self.raise_no_permission_to(permlevel or permtype)
  File "apps/frappe/frappe/model/document.py", line 215, in raise_no_permission_to
    raise frappe.PermissionError
frappe.exceptions.PermissionError



\b'{"customer": "John Doe", "items": [{"item_code": "Item001", "qty": 5}]}'n

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 85, in application
    frappe.api.validate_auth()
  File "apps/frappe/frappe/api.py", line 178, in validate_auth
    validate_auth_via_api_keys(authorization_header)
  File "apps/frappe/frappe/api.py", line 235, in validate_auth_via_api_keys
    validate_api_key_secret(api_key, api_secret, authorization_source)
  File "apps/frappe/frappe/api.py", line 253, in validate_api_key_secret
    doc_secret = frappe.utils.password.get_decrypted_password(doctype, doc, fieldname="api_secret")
  File "apps/frappe/frappe/utils/password.py", line 65, in get_decrypted_password
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 528, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 445, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.AuthenticationError: Password not found for User None api_secret

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 85, in application
    frappe.api.validate_auth()
  File "apps/frappe/frappe/api.py", line 178, in validate_auth
    validate_auth_via_api_keys(authorization_header)
  File "apps/frappe/frappe/api.py", line 235, in validate_auth_via_api_keys
    validate_api_key_secret(api_key, api_secret, authorization_source)
  File "apps/frappe/frappe/api.py", line 253, in validate_api_key_secret
    doc_secret = frappe.utils.password.get_decrypted_password(doctype, doc, fieldname="api_secret")
  File "apps/frappe/frappe/utils/password.py", line 65, in get_decrypted_password
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 528, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 445, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.AuthenticationError: Password not found for User None api_secret

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 85, in application
    frappe.api.validate_auth()
  File "apps/frappe/frappe/api.py", line 178, in validate_auth
    validate_auth_via_api_keys(authorization_header)
  File "apps/frappe/frappe/api.py", line 235, in validate_auth_via_api_keys
    validate_api_key_secret(api_key, api_secret, authorization_source)
  File "apps/frappe/frappe/api.py", line 253, in validate_api_key_secret
    doc_secret = frappe.utils.password.get_decrypted_password(doctype, doc, fieldname="api_secret")
  File "apps/frappe/frappe/utils/password.py", line 65, in get_decrypted_password
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 528, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 445, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.AuthenticationError: Password not found for User None api_secret



\b'{"customer": "John Doe", "items": [{"item_code": "Item001", "qty": 5}]}'n

Traceback (most recent call last):
  File "apps/frappe/frappe/modules/utils.py", line 245, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
  File "apps/frappe/frappe/__init__.py", line 1330, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'frappe.core.doctype.yourresourcetype'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 142, in handle
    doc = frappe.get_doc(data).insert()
  File "apps/frappe/frappe/__init__.py", line 1187, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 72, in get_doc
    controller = get_controller(doctype)
  File "apps/frappe/frappe/model/base_document.py", line 82, in get_controller
    site_controllers[doctype] = _get_controller()
  File "apps/frappe/frappe/model/base_document.py", line 64, in _get_controller
    module = load_doctype_module(doctype, module_name)
  File "apps/frappe/frappe/modules/utils.py", line 249, in load_doctype_module
    raise ImportError(msg) from e
ImportError: Module import failed for YourResourceType, the DocType you're trying to open might be deleted.<br> Error: No module named 'frappe.core.doctype.yourresourcetype'

Updating Dashboard for frappe
Updating Dashboard for erpnext
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1610, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 28, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 327, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 251, in insert
    self._validate_links()
  File "apps/frappe/frappe/model/document.py", line 882, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
  File "apps/frappe/frappe/__init__.py", line 528, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 445, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.LinkValidationError: Could not find Default Letter Head: Pranav Patel 3

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1610, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 232, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 90, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 71, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 131, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/selling/report/sales_order_trends/sales_order_trends.py", line 14, in execute
    conditions = get_columns(filters, "Sales Order")
  File "apps/erpnext/erpnext/controllers/trends.py", line 11, in get_columns
    validate_filters(filters)
  File "apps/erpnext/erpnext/controllers/trends.py", line 50, in validate_filters
    frappe.throw(_("{0} is mandatory").format(f))
  File "apps/frappe/frappe/__init__.py", line 528, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 445, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Fiscal Year is mandatory

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1610, in call
    return fn(*args, **newargs)
TypeError: get_children() missing 1 required positional argument: 'company'

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1610, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 232, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 90, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 71, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 131, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/selling/report/sales_order_trends/sales_order_trends.py", line 14, in execute
    conditions = get_columns(filters, "Sales Order")
  File "apps/erpnext/erpnext/controllers/trends.py", line 11, in get_columns
    validate_filters(filters)
  File "apps/erpnext/erpnext/controllers/trends.py", line 50, in validate_filters
    frappe.throw(_("{0} is mandatory").format(f))
  File "apps/frappe/frappe/__init__.py", line 528, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 445, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Fiscal Year is mandatory

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1610, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 232, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 90, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 71, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 131, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/profit_and_loss_statement/profit_and_loss_statement.py", line 18, in execute
    period_list = get_period_list(
  File "apps/erpnext/erpnext/accounts/report/financial_statements.py", line 38, in get_period_list
    validate_fiscal_year(fiscal_year, from_fiscal_year, to_fiscal_year)
  File "apps/erpnext/erpnext/accounts/report/financial_statements.py", line 122, in validate_fiscal_year
    frappe.throw(_("Start Year and End Year are mandatory"))
  File "apps/frappe/frappe/__init__.py", line 528, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 445, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Start Year and End Year are mandatory

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1610, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 232, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 90, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 71, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 131, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/profit_and_loss_statement/profit_and_loss_statement.py", line 18, in execute
    period_list = get_period_list(
  File "apps/erpnext/erpnext/accounts/report/financial_statements.py", line 38, in get_period_list
    validate_fiscal_year(fiscal_year, from_fiscal_year, to_fiscal_year)
  File "apps/erpnext/erpnext/accounts/report/financial_statements.py", line 122, in validate_fiscal_year
    frappe.throw(_("Start Year and End Year are mandatory"))
  File "apps/frappe/frappe/__init__.py", line 528, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 445, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Start Year and End Year are mandatory

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1610, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 232, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 90, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 71, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 131, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/selling/report/sales_order_trends/sales_order_trends.py", line 14, in execute
    conditions = get_columns(filters, "Sales Order")
  File "apps/erpnext/erpnext/controllers/trends.py", line 11, in get_columns
    validate_filters(filters)
  File "apps/erpnext/erpnext/controllers/trends.py", line 50, in validate_filters
    frappe.throw(_("{0} is mandatory").format(f))
  File "apps/frappe/frappe/__init__.py", line 528, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 445, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Fiscal Year is mandatory

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1610, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 232, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 90, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 71, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 131, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/buying/report/purchase_order_trends/purchase_order_trends.py", line 14, in execute
    conditions = get_columns(filters, "Purchase Order")
  File "apps/erpnext/erpnext/controllers/trends.py", line 11, in get_columns
    validate_filters(filters)
  File "apps/erpnext/erpnext/controllers/trends.py", line 50, in validate_filters
    frappe.throw(_("{0} is mandatory").format(f))
  File "apps/frappe/frappe/__init__.py", line 528, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 445, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Fiscal Year is mandatory

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1610, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 232, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 90, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 71, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 131, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/profit_and_loss_statement/profit_and_loss_statement.py", line 18, in execute
    period_list = get_period_list(
  File "apps/erpnext/erpnext/accounts/report/financial_statements.py", line 38, in get_period_list
    validate_fiscal_year(fiscal_year, from_fiscal_year, to_fiscal_year)
  File "apps/erpnext/erpnext/accounts/report/financial_statements.py", line 122, in validate_fiscal_year
    frappe.throw(_("Start Year and End Year are mandatory"))
  File "apps/frappe/frappe/__init__.py", line 528, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 445, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Start Year and End Year are mandatory

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1610, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 232, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 90, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 71, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 131, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/selling/report/sales_order_trends/sales_order_trends.py", line 14, in execute
    conditions = get_columns(filters, "Sales Order")
  File "apps/erpnext/erpnext/controllers/trends.py", line 11, in get_columns
    validate_filters(filters)
  File "apps/erpnext/erpnext/controllers/trends.py", line 50, in validate_filters
    frappe.throw(_("{0} is mandatory").format(f))
  File "apps/frappe/frappe/__init__.py", line 528, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 445, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Fiscal Year is mandatory

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1610, in call
    return fn(*args, **newargs)
TypeError: get_children() missing 1 required positional argument: 'company'

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1610, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 232, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 90, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 71, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 131, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/profit_and_loss_statement/profit_and_loss_statement.py", line 18, in execute
    period_list = get_period_list(
  File "apps/erpnext/erpnext/accounts/report/financial_statements.py", line 38, in get_period_list
    validate_fiscal_year(fiscal_year, from_fiscal_year, to_fiscal_year)
  File "apps/erpnext/erpnext/accounts/report/financial_statements.py", line 122, in validate_fiscal_year
    frappe.throw(_("Start Year and End Year are mandatory"))
  File "apps/frappe/frappe/__init__.py", line 528, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 445, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Start Year and End Year are mandatory

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1610, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 232, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 90, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 71, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 131, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/profit_and_loss_statement/profit_and_loss_statement.py", line 18, in execute
    period_list = get_period_list(
  File "apps/erpnext/erpnext/accounts/report/financial_statements.py", line 38, in get_period_list
    validate_fiscal_year(fiscal_year, from_fiscal_year, to_fiscal_year)
  File "apps/erpnext/erpnext/accounts/report/financial_statements.py", line 122, in validate_fiscal_year
    frappe.throw(_("Start Year and End Year are mandatory"))
  File "apps/frappe/frappe/__init__.py", line 528, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 445, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Start Year and End Year are mandatory

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1610, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 232, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 90, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 71, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 131, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/selling/report/sales_order_trends/sales_order_trends.py", line 14, in execute
    conditions = get_columns(filters, "Sales Order")
  File "apps/erpnext/erpnext/controllers/trends.py", line 11, in get_columns
    validate_filters(filters)
  File "apps/erpnext/erpnext/controllers/trends.py", line 50, in validate_filters
    frappe.throw(_("{0} is mandatory").format(f))
  File "apps/frappe/frappe/__init__.py", line 528, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 445, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Fiscal Year is mandatory

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1610, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 232, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 90, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 71, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 131, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/profit_and_loss_statement/profit_and_loss_statement.py", line 18, in execute
    period_list = get_period_list(
  File "apps/erpnext/erpnext/accounts/report/financial_statements.py", line 38, in get_period_list
    validate_fiscal_year(fiscal_year, from_fiscal_year, to_fiscal_year)
  File "apps/erpnext/erpnext/accounts/report/financial_statements.py", line 122, in validate_fiscal_year
    frappe.throw(_("Start Year and End Year are mandatory"))
  File "apps/frappe/frappe/__init__.py", line 528, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 445, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Start Year and End Year are mandatory

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1610, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 232, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 90, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 71, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 131, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/profit_and_loss_statement/profit_and_loss_statement.py", line 18, in execute
    period_list = get_period_list(
  File "apps/erpnext/erpnext/accounts/report/financial_statements.py", line 38, in get_period_list
    validate_fiscal_year(fiscal_year, from_fiscal_year, to_fiscal_year)
  File "apps/erpnext/erpnext/accounts/report/financial_statements.py", line 122, in validate_fiscal_year
    frappe.throw(_("Start Year and End Year are mandatory"))
  File "apps/frappe/frappe/__init__.py", line 528, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 445, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Start Year and End Year are mandatory

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1610, in call
    return fn(*args, **newargs)
TypeError: get_children() missing 1 required positional argument: 'company'

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1610, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 232, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 90, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 71, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 131, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/profit_and_loss_statement/profit_and_loss_statement.py", line 18, in execute
    period_list = get_period_list(
  File "apps/erpnext/erpnext/accounts/report/financial_statements.py", line 38, in get_period_list
    validate_fiscal_year(fiscal_year, from_fiscal_year, to_fiscal_year)
  File "apps/erpnext/erpnext/accounts/report/financial_statements.py", line 122, in validate_fiscal_year
    frappe.throw(_("Start Year and End Year are mandatory"))
  File "apps/frappe/frappe/__init__.py", line 528, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 445, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Start Year and End Year are mandatory

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1610, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 232, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 90, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 71, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 131, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/profit_and_loss_statement/profit_and_loss_statement.py", line 18, in execute
    period_list = get_period_list(
  File "apps/erpnext/erpnext/accounts/report/financial_statements.py", line 38, in get_period_list
    validate_fiscal_year(fiscal_year, from_fiscal_year, to_fiscal_year)
  File "apps/erpnext/erpnext/accounts/report/financial_statements.py", line 122, in validate_fiscal_year
    frappe.throw(_("Start Year and End Year are mandatory"))
  File "apps/frappe/frappe/__init__.py", line 528, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 445, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Start Year and End Year are mandatory

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1610, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 232, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 90, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 71, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 131, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/buying/report/purchase_order_trends/purchase_order_trends.py", line 14, in execute
    conditions = get_columns(filters, "Purchase Order")
  File "apps/erpnext/erpnext/controllers/trends.py", line 11, in get_columns
    validate_filters(filters)
  File "apps/erpnext/erpnext/controllers/trends.py", line 50, in validate_filters
    frappe.throw(_("{0} is mandatory").format(f))
  File "apps/frappe/frappe/__init__.py", line 528, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 445, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Fiscal Year is mandatory

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1610, in call
    return fn(*args, **newargs)
TypeError: get_children() missing 1 required positional argument: 'company'

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1610, in call
    return fn(*args, **newargs)
TypeError: get_children() missing 1 required positional argument: 'company'

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1610, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 232, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 90, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 71, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 131, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/profit_and_loss_statement/profit_and_loss_statement.py", line 18, in execute
    period_list = get_period_list(
  File "apps/erpnext/erpnext/accounts/report/financial_statements.py", line 38, in get_period_list
    validate_fiscal_year(fiscal_year, from_fiscal_year, to_fiscal_year)
  File "apps/erpnext/erpnext/accounts/report/financial_statements.py", line 122, in validate_fiscal_year
    frappe.throw(_("Start Year and End Year are mandatory"))
  File "apps/frappe/frappe/__init__.py", line 528, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 445, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Start Year and End Year are mandatory

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1610, in call
    return fn(*args, **newargs)
TypeError: get_children() missing 1 required positional argument: 'company'

{'item_code': 'test_Item', 'item_name': 'Test Item Name', 'description': 'This is a new item created via webhook', 'stock_uom': 'Nos'}
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1610, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 232, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 90, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 71, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 131, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/profit_and_loss_statement/profit_and_loss_statement.py", line 18, in execute
    period_list = get_period_list(
  File "apps/erpnext/erpnext/accounts/report/financial_statements.py", line 38, in get_period_list
    validate_fiscal_year(fiscal_year, from_fiscal_year, to_fiscal_year)
  File "apps/erpnext/erpnext/accounts/report/financial_statements.py", line 122, in validate_fiscal_year
    frappe.throw(_("Start Year and End Year are mandatory"))
  File "apps/frappe/frappe/__init__.py", line 528, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 445, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Start Year and End Year are mandatory

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 85, in application
    frappe.api.validate_auth()
  File "apps/frappe/frappe/api.py", line 178, in validate_auth
    validate_auth_via_api_keys(authorization_header)
  File "apps/frappe/frappe/api.py", line 235, in validate_auth_via_api_keys
    validate_api_key_secret(api_key, api_secret, authorization_source)
  File "apps/frappe/frappe/api.py", line 253, in validate_api_key_secret
    doc_secret = frappe.utils.password.get_decrypted_password(doctype, doc, fieldname="api_secret")
  File "apps/frappe/frappe/utils/password.py", line 65, in get_decrypted_password
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 528, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 445, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.AuthenticationError: Password not found for User None api_secret

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1610, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 232, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 792, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 90, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 71, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 131, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/accounts/report/profit_and_loss_statement/profit_and_loss_statement.py", line 18, in execute
    period_list = get_period_list(
  File "apps/erpnext/erpnext/accounts/report/financial_statements.py", line 38, in get_period_list
    validate_fiscal_year(fiscal_year, from_fiscal_year, to_fiscal_year)
  File "apps/erpnext/erpnext/accounts/report/financial_statements.py", line 122, in validate_fiscal_year
    frappe.throw(_("Start Year and End Year are mandatory"))
  File "apps/frappe/frappe/__init__.py", line 528, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 445, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Start Year and End Year are mandatory

Net 30
Net 30
Net 30
Net 30
Net 30
Net 30
Net 30
Net 30
Net 30
Net 30
Net 30
Net 30
Net 30
Net 30
Net 30
Net 30
Net 30
Net 30
Net 30
Net 30
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 85, in application
    frappe.api.validate_auth()
  File "apps/frappe/frappe/api.py", line 178, in validate_auth
    validate_auth_via_api_keys(authorization_header)
  File "apps/frappe/frappe/api.py", line 235, in validate_auth_via_api_keys
    validate_api_key_secret(api_key, api_secret, authorization_source)
  File "apps/frappe/frappe/api.py", line 253, in validate_api_key_secret
    doc_secret = frappe.utils.password.get_decrypted_password(doctype, doc, fieldname="api_secret")
  File "apps/frappe/frappe/utils/password.py", line 65, in get_decrypted_password
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 528, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 445, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.AuthenticationError: Password not found for User None api_secret

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 85, in application
    frappe.api.validate_auth()
  File "apps/frappe/frappe/api.py", line 178, in validate_auth
    validate_auth_via_api_keys(authorization_header)
  File "apps/frappe/frappe/api.py", line 235, in validate_auth_via_api_keys
    validate_api_key_secret(api_key, api_secret, authorization_source)
  File "apps/frappe/frappe/api.py", line 253, in validate_api_key_secret
    doc_secret = frappe.utils.password.get_decrypted_password(doctype, doc, fieldname="api_secret")
  File "apps/frappe/frappe/utils/password.py", line 65, in get_decrypted_password
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 528, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 496, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 445, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.AuthenticationError: Password not found for User None api_secret

